# ruff: noqa: F401, E402
"""
Django settings for LAcon V project.

Generated by copier.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import bleach.sanitizer
import djp

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure logs directory exists
LOGS_DIR = BASE_DIR / ".local" / "logs"
LOGS_DIR.mkdir(parents=True, exist_ok=True)


# Environment variable helpers
def get_string(key, default=None):
    return os.environ.get(key, default)


def get_required_string(key):
    return os.environ[key]


def get_int(key, default=None):
    value = os.environ.get(key, default)
    return int(value) if value is not None else None


def get_bool(key, default=False):
    return os.environ.get(key, str(default)).lower() in ("true", "1", "yes")


def get_string_list(key, default=None):
    return (
        os.environ.get(key, "").split(",") if os.environ.get(key) else (default or [])
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_required_string("NOM_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool("NOM_DEBUG")
TEMPLATE_DEBUG = DEBUG

if DEBUG:
    try:
        from icecream.builtins import install as install_icecream

        install_icecream()
    except ImportError:
        ...


class InvalidStringShowWarning(str):
    def __mod__(self, other):
        import logging

        logger = logging.getLogger(__name__)
        logger.warning(
            f"In template, undefined variable or unknown value for: '{other}'"
        )
        return ""

    def __bool__(self):  # if using Python 2, use __nonzero__ instead
        # make the template tag `default` use its fallback value
        return False


ALLOWED_HOSTS = get_string_list("NOM_ALLOWED_HOSTS")

CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS] if ALLOWED_HOSTS else []

# Application definition

INSTALLED_APPS = [
    "config.apps.LaconVAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    # Use whitenoise to serve static files
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    # deferred tasks
    "django_celery_results",
    "django_celery_beat",
    # debug helper
    "django_extensions",
    "django_browser_reload",
    "debug_toolbar",
    # to render markdown to HTML in templates
    "markdownify.apps.MarkdownifyConfig",
    # OAuth login
    "social_django",
    # Admin filtering enhancements
    "admin_auto_filters",
    # Admin forms
    "django_admin_action_forms",
    # Admin audit logging
    "logentry_admin",
    # Theming
    "django_bootstrap5",
    "bootstrap",
    "fontawesome",
    # Fonts
    "django_google_fonts",
    # HTMX support
    "django_htmx",
    # A healthcheck
    "watchman",
    # Markdown field support
    "markdownfield",
    # Feature flags
    "waffle",
    # the convention theme; this MUST come before the nominate app, so that its templates can
    # override the nominate ones.
    "lacon_v_app",
    # nomnom's base templates and code"
    "nomnom.base",
    # The nominating and voting app
    "nomnom.nominate",
    "nomnom.canonicalize",
    # Consultative Votes
    "nomnom.advise",
    # The hugo packet app
    "nomnom.hugopacket",
    "nomnom.convention_admin",
]

SITE_ID = 1

NOMNOM_ALLOW_USERNAME_LOGIN_FOR_MEMBERS = get_bool("NOM_ALLOW_USERNAME_LOGIN")

AUTHENTICATION_BACKENDS = [
    "lacon_v_app.auth.LaconMemberBackend",
    "django.contrib.auth.backends.ModelBackend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "nomnom.middleware.HtmxMessageMiddleware",
    "waffle.middleware.WaffleMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
                "nomnom.nominate.context_processors.site",
                "nomnom.nominate.context_processors.inject_login_form",
            ],
            "string_if_invalid": InvalidStringShowWarning("%s"),
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": get_required_string("NOM_DB_NAME"),
        "USER": get_required_string("NOM_DB_USER"),
        "PASSWORD": get_required_string("NOM_DB_PASSWORD"),
        "HOST": get_required_string("NOM_DB_HOST"),
        "PORT": str(get_int("NOM_DB_PORT")),
        "DISABLE_SERVER_SIDE_CURSORS": True,
    }
}

# reuse some of those DB connections
if not DEBUG:
    CONN_HEALTH_CHECKS = True
    CONN_MAX_AGE = 600

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{get_required_string('NOM_REDIS_HOST')}:{get_int('NOM_REDIS_PORT')}",
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGOUT_REDIRECT_URL = "index"

# we are using postgres, so this is recommended in the docs.
SOCIAL_AUTH_JSONFIELD_ENABLED = True

# Social authentication is configured using Authentik OIDC

# Common social auth settings
# Use the generic LOGIN_ERROR_URL instead of backend-specific SOCIAL_AUTH_LACON_LOGIN_ERROR_URL
# due to https://github.com/python-social-auth/social-core/issues/875
SOCIAL_AUTH_LOGIN_ERROR_URL = "election:login_error"

SOCIAL_AUTH_ADMIN_USER_SEARCH_FIELDS = ["username", "first_name", "email"]

SOCIAL_AUTH_LACON_KEY = get_required_string("NOM_OAUTH_CLIENT_ID")
SOCIAL_AUTH_LACON_SECRET = get_required_string("NOM_OAUTH_CLIENT_SECRET")
SOCIAL_AUTH_LACON_OIDC_ENDPOINT = get_string(
    "NOM_AUTHENTIK_OIDC_ENDPOINT",
    "https://auth.lacon.org/application/o/nom-nom-production",
)
SOCIAL_AUTH_LACON_INVALIDATION_ENDPOINT = get_string(
    "NOM_AUTHENTIK_INVALIDATION_ENDPOINT",
    "https://auth.lacon.org/flows/-/default/invalidation/",
)
SOCIAL_AUTH_LACON_JWKS_URI = get_string(
    "NOM_AUTHENTIK_JWKS_URI",
    f"{SOCIAL_AUTH_LACON_OIDC_ENDPOINT}/jwks/",
)

# Social authentication pipeline
SOCIAL_AUTH_PIPELINE = [
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "lacon_v_app.auth.adapt_regid_to_username",
    "social_core.pipeline.user.get_username",
    "lacon_v_app.auth.adapt_personal_information",
    "lacon_v_app.auth.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "lacon_v_app.auth.get_wsfs_permissions",
    "lacon_v_app.auth.update_user_details",
    "lacon_v_app.auth.set_member_details",
    "nomnom.nominate.social_auth.pipeline.set_user_wsfs_membership",
    "nomnom.nominate.social_auth.pipeline.add_election_permissions",
    "lacon_v_app.auth.store_oidc_session_mapping",
]

# Session configuration
# Set session duration to 6 months (180 days)
SESSION_COOKIE_AGE = 180 * 24 * 60 * 60  # 15552000 seconds

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = get_string("NOM_STATIC_FILE_ROOT", "staticfiles")
GOOGLE_FONTS_DIR = BASE_DIR / "lacon_v_app" / "static" / "google_fonts"
STATICFILES_DIRS = [GOOGLE_FONTS_DIR]

# Use Whitenoise's storage backend for better static file handling
# This adds cache-busting hashes to filenames and handles updates properly
if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Async tasks
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "default"
CELERY_BROKER_URL = (
    f"redis://{get_required_string('NOM_REDIS_HOST')}:{get_int('NOM_REDIS_PORT')}"
)
CELERY_TIMEZONE = "America/Los_Angeles"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Presentation
ADMIN_MANAGED_ATTRIBUTES = bleach.sanitizer.ALLOWED_ATTRIBUTES.copy()
ADMIN_MANAGED_ATTRIBUTES.update(
    {
        "span": bleach.sanitizer.ALLOWED_ATTRIBUTES.get("span", []) + ["lang"],
        "p": bleach.sanitizer.ALLOWED_ATTRIBUTES.get("p", []) + ["lang"],
        "div": bleach.sanitizer.ALLOWED_ATTRIBUTES.get("div", []) + ["lang"],
    }
)
ADMIN_ALERT_ATTRIBUTES = ADMIN_MANAGED_ATTRIBUTES.copy()
ADMIN_ALERT_ATTRIBUTES["div"] += ["class", "role"]

MARKDOWNIFY = {
    "default": {
        "WHITELIST_TAGS": bleach.sanitizer.ALLOWED_TAGS | {"p", "h4", "h5"},
    },
    "admin-content": {
        "WHITELIST_TAGS": bleach.sanitizer.ALLOWED_TAGS | {"p", "h4", "h5", "span"},
        "WHITELIST_ATTRS": ADMIN_MANAGED_ATTRIBUTES,
    },
    "admin-alert": {
        "WHITELIST_TAGS": bleach.sanitizer.ALLOWED_TAGS
        | {"p", "h4", "h5", "span", "div"},
        "WHITELIST_ATTRS": ADMIN_ALERT_ATTRIBUTES,
    },
    "admin-label": {
        # no block-level elements
        "WHITELIST_TAGS": bleach.sanitizer.ALLOWED_TAGS
        | {"span"} - {"blockquote", "ol", "li", "ul"}
        | {"s"},
        "WHITELIST_ATTRS": ADMIN_MANAGED_ATTRIBUTES,
    },
}

MARKDOWN_EXTENSIONS = [
    "pymdownx.tilde",
]


BOOTSTRAP5 = {
    "field_renderers": {
        "default": "django_bootstrap5.renderers.FieldRenderer",
        "blank-safe": "nomnom.nominate.renderers.BlankSafeFieldRenderer",
    },
}

GOOGLE_FONTS = [
    "Poppins",
    "Nunito",
]

# Email
EMAIL_HOST = get_string("NOM_EMAIL_HOST")
EMAIL_PORT = get_int("NOM_EMAIL_PORT")
EMAIL_HOST_USER = get_string("NOM_EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = get_string("NOM_EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = get_bool("NOM_EMAIL_USE_TLS")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "file": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "debug_console": {
            "level": "DEBUG",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "serve.log",
            "formatter": "file",
        },
    },
    "root": {
        "level": "INFO",
        "handlers": ["console", "file"],
    },
    "loggers": {
        "django.db.backends": {
            "level": "DEBUG",
            "handlers": ["debug_console"],
            "propagate": False,
        },
        "django": {
            "level": "INFO",
            "handlers": ["console", "file"],
            "propagate": False,
        },
    },
}


# Sentry
if get_string("NOM_SENTRY_SDK_DSN"):
    import sentry_sdk

    sentry_sdk.init(
        dsn=get_required_string("NOM_SENTRY_SDK_DSN"),
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        traces_sample_rate=1.0,
        # Set profiles_sample_rate to 1.0 to profile 100%
        # of sampled transactions.
        # We recommend adjusting this value in production.
        profiles_sample_rate=1.0,
        # Our environment
        environment=get_string("NOM_SENTRY_SDK_ENVIRONMENT", "development"),
        # include the user and client IP
        send_default_pii=True,
    )

if DEBUG:
    INTERNAL_IPS = [
        "127.0.0.1",
    ]

# Seed data can come from here:
FIXTURE_DIRS = [BASE_DIR / "seed"]

try:
    from .settings_override import *  # noqa: F403
except ImportError:
    ...

# Packet configuration
HUGOPACKET_AWS_REGION = "sfo3"
HUGOPACKET_AWS_ENDPOINT = "https://sfo3.digitaloceanspaces.com/"

djp.settings(globals())
